import { Box, Button, Container, Typography } from '@mui/material'
import { Inter } from '@next/font/google'
import { signIn, signOut, useSession } from 'next-auth/react'
import Head from 'next/head'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { data: session } = useSession()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container maxWidth="lg">
          <Box
            sx={{
              my: 4,
              display: 'flex',
              flexDirection: 'column',
              justifyContent: 'center',
              alignItems: 'center',
            }}
          >
            <Typography variant="h4" component="h1" gutterBottom>
              MUI v5 + Next.js with TypeScript example
            </Typography>
            <Link href="/assignments" color="secondary" passHref>
              <Button variant={'contained'}>Go to the assignments</Button>
            </Link>
            <Button
              variant={'outlined'}
              href="/"
              onClick={() => (session ? signOut() : signIn())}
              sx={{ mt: 2 }}
            >
              Sign {session ? 'out' : 'in'}
            </Button>
          </Box>
        </Container>
      </main>
    </>
  )
}
